
export let FORM_CONVENIO = {
    titulo: 'Convenio',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Convenio',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label_i18n: 'id',
        placeholder_i18n: 'id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'selectmultiple',
        claseGrid: 'col-6',
        nombre: 'Organizacion',
        label_i18n: 'organizacion',
        placeholder_i18n: 'organizacion',
        requerido: true,
        tipo: 'Organizacion',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'selectmultiple',
        claseGrid: 'col-6',
        nombre: 'Tipoconvenio',
        label_i18n: 'tipoconvenio',
        placeholder_i18n: 'tipoconvenio',
        requerido: true,
        tipo: 'Tipoconvenio',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'selectmultiple',
        claseGrid: 'col-6',
        nombre: 'Pais',
        label_i18n: 'pais',
        placeholder_i18n: 'pais',
        requerido: true,
        tipo: 'Pais',
        // key: 'Name',
        opciones: [],
    },
    ],
}
