
export let FORM_MOVILIDAD = {
    titulo: 'Movilidad',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Movilidad',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label_i18n: 'id',
        placeholder_i18n: 'id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Presupuesto',
        label_i18n: 'presupuesto',
        placeholder_i18n: 'presupuesto',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'Fechainicio',
        label_i18n: 'fechainicio',
        placeholder_i18n: 'fechainicio',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'Fechafinal',
        label_i18n: 'fechafinal',
        placeholder_i18n: 'fechafinal',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Persona',
        label_i18n: 'persona',
        placeholder_i18n: 'persona',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Convenio',
        label_i18n: 'convenio',
        placeholder_i18n: 'convenio',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'Idtipomovilidad',
        label_i18n: 'idtipomovilidad',
        placeholder_i18n: 'idtipomovilidad',
        requerido: true,
        tipo: 'Tipomovilidad',
        // key: 'Name',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'Idtipocategoria',
        label_i18n: 'idtipocategoria',
        placeholder_i18n: 'idtipocategoria',
        requerido: true,
        tipo: 'Tipocategoria',
        key: 'Nombre',
        opciones: [],
    },
    ],
}
