
export let FORM_ESTADOS = {
    titulo: 'Estados',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Estados',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label_i18n: 'id',
        placeholder_i18n: 'id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Nombre',
        label_i18n: 'nombre',
        placeholder_i18n: 'nombre',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Descripcion',
        label_i18n: 'descripcion',
        placeholder_i18n: 'descripcion',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Codigoabreavicion',
        label_i18n: 'codigoabreavicion',
        placeholder_i18n: 'codigoabreavicion',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Activo',
        label_i18n: 'activo',
        placeholder_i18n: 'activo',
        requerido: true,
        tipo: 'checkbox',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Numeroorden',
        label_i18n: 'numeroorden',
        placeholder_i18n: 'numeroorden',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'Fechacreacion',
        label_i18n: 'fechacreacion',
        placeholder_i18n: 'fechacreacion',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'Fechamodificacion',
        label_i18n: 'fechamodificacion',
        placeholder_i18n: 'fechamodificacion',
        requerido: true,
        tipo: 'date',
    },
    ],
}
